### PR TITLE
fix(ENG-878): introduce husky and commit lint

### PR DESCRIPTION
**Pull request by triwats**
## Description

1. Introduce Husky
2. Introduce Conventional Commit Lint

## Issue(s)

[ENG-878](https://www.notion.so/oaknationalacademy/Add-Commit-Lint-Husky-into-Terraform-Actions-Repo-71007b3423a04ffb9dc142317eacd7f6?pvs=4)

## How to test

1. Make a commit, or run: 

```
 ~/src/oak/oak-terraform-actions  ENG-878                                                                                     22.6.0  12:52:48
❯ echo "lol this is wrong" | commitlint
⧗   input: lol this is wrong
✖   subject may not be empty [subject-empty]
✖   type may not be empty [type-empty]

✖   found 2 problems, 0 warnings
ⓘ   Get help: https://github.com/conventional-changelog/commitlint/#what-is-commitlint
```

### CODE REVIEW

**Comment by triwats** [comment]
Relies on #3 being merged to fix issues surrounding the linting of the yml files themselves.

**Comment by simonrose121** [comment]
Are we planning on adding semantic release too? Or was that the question around versioning?

**Review by simonrose121 — APPROVED** [review]
Works locally for me.

**Comment by triwats** [comment]
> Are we planning on adding semantic release too? Or was that the question around versioning?

Good question! I'll bang in another task for that to pick up rather than that as not sure how it's done just yet.

EDIT: Added ticket to add semantic release: https://www.notion.so/oaknationalacademy/Add-Semantic-Release-to-Github-Actions-c0c9f8e6d0ed43858b44e01972ae881d?pvs=4

**Pull request merged**
